### ISSUE TITLE
release() mehod does not release the microphone from browser

### ISSUE THREAD

**Issue by ghost** [Picovoice/web-voice-processor#5] opened 2021-04-24 21:33 UTC
When I call release() for deallocate component, the microphone on browser stay opened.
I have tested on Chrome with vue.js Porcupine.vue

I solved to call  before release in Porcupine.vue file:

this.webVp.audioSource.mediaStream.getTracks().forEach(track => track.stop());
this.webVp.release(); 

Is possible when call pause() release microphone and  on resume() reattach it?

In mobile browser like IOS Safari there are problem: if I access microphone for other task I loose  microphone in porcupine.
In mobile browser like Chrome Android, if microphone are used, Google webkitSpeechRecognition not work.

**Comment by dbartle** [comment] 2021-04-24 22:17
Thanks for the report, this makes sense. It should close it down entirely when release() is called, for sure.

"Is possible when call pause() release microphone and on resume() reattach it?"

I think it would make more sense to create a new method stop() that destroys the microphone and keep pause() working as-is. Re acquiring the stream might hurt latency and cause some difficulties for the deps that assume pause/resume is essentially instant/cheap. Then start can be re-worked to re-acquire the stream, if necessary.

**Comment by ghost** [comment] 2021-04-24 22:48
That's right, it makes more sense to create a stop method and reacquire the microphone with start

**Comment by dbartle** [comment] 2021-04-30 22:12
This has been fixed in v2.0.3. Calling release() will now stop the media tracks.

I haven't yet added a stop() method, because it will lead to behaviour that requires a lot more testing and changes, because it modifies the underlying assumption that once a WebVoiceProcessor instance exists, it has already successfully completed the async mic acquisition. We can look at doing that in a separate issue/task potentially.

**Comment by dbartle** [comment] 2021-04-30 22:23
The Vue binding has also been updated. The web-voice-processor has been set to a peerDependency, so this means that it will need to be explicitly installed, but now it should be less coupled to the binding.

**Comment by dbartle** [comment] 2021-05-03 18:24
I'm going to close this as the issue is resolved for the original topic.

**Closed as completed by dbartle** 2021-05-03 18:24 UTC
Labels: bug, enhancement
